[project]
name = "kklogger"
version = "1.0.0"
requires-python = ">= 3.12"
description = "My logger package."

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
rmlog = "kklogger.main:rmlog"
